version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: jobtrackr-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: jobtrackrpro
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
