version: '3.8'
services:
  web:
    image: your-web-app-image
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_HOST=http://localhost:3000
    env_file:
      - ./.env
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=jobtrackrpro
